version: '3.8'

#TODO: Разобраться с healthcheck, потому что нет уверенности что он вообще работает
services:
  database:
    image: mysql:8.3.0
    ports:
      - '3306:3306'
    restart: on-failure
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      MYSQL_DATABASE: file-storage
      MYSQL_USER: aselium
      MYSQL_PASSWORD: new
      MYSQL_ROOT_PASSWORD: new
    volumes:
      - ${MYSQL_VOLUME_PATH}:/var/lib/database
    networks:
      - app_network

  minio:
    image: minio/minio:RELEASE.2024-03-21T23-13-43Z.fips
    ports:
      - '9000:9000'
      - '9001:9001'
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      - MINIO_ROOT_USER=aselium
      - MINIO_ROOT_PASSWORD=newpassword
      - MINIO_DEFAULT_BUCKETS=file-storage
    volumes:
      - ${MINIO_VOLUME_PATH}:/var/lib/minio
      - ${CERTIFICATE}:/root/.minio/certs
    command: minio server ${MINIO_VOLUME_PATH}:/data --console-address :9001
    networks:
      - app_network

  redis:
    image: redis:7.2-alpine
    ports:
      - '6379:6379'
    restart: on-failure
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 20s
      retries: 3
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
